repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^bot/.*\.py$
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [ python ]
        files: ^bot/.*\.py$
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        files: ^bot/.*\.py$
